package treasurypublish

import scalus.cardano.address.{Address, ShelleyAddress, ShelleyPaymentPart}
import java.time.Instant

// Port of params/common.ts + params/preprod.ts (+ preview re-export). Pure
// functions of static input — every call returns identical bytes, so script
// hashes are stable across init and every subsequent invocation.

enum Net {
    case Preview, Preprod, Mainnet

    /** Blockfrost URL prefix / project-id prefix (network-scoped). */
    def slug: String = this match
        case Preview => "preview"
        case Preprod => "preprod"
        case Mainnet => "mainnet"
}

final case class RawConfig(
    network: Net,
    adminAddress: String,
    boardPkhs: Seq[String], // exactly 3, hex pkhs (K_1, K_2, K_3)
    fluidTokensPkh: String, // FluidTokens vendor pkh (hex, 56 chars)
    amountLovelace: BigInt,
    treasuryExpirationISO: String,
    vendorExpirationGraceDays: Int
)

final case class ResolvedConfig(
    network: Net,
    adminAddress: String,
    adminPkhHex: String,
    boardPkhs: Seq[String],
    fluidTokensPkh: String,
    amountLovelace: BigInt,
    treasuryExpirationMs: BigInt,
    vendorExpirationMs: BigInt,
    vendorPayoutUpperboundMs: BigInt
)

object Config {
    private val MsPerDay: Long = 24L * 60 * 60 * 1000

    /** Payment key hash (hex, 56 chars) from a Shelley base/enterprise address. */
    def addressPaymentKeyHash(addr: String): String = Address.fromBech32(addr) match
        case sh: ShelleyAddress =>
            sh.payment match
                case ShelleyPaymentPart.Key(h) => h.toHex
                case _ => sys.error(s"$addr payment part is a script hash, not a key hash")
        case other => sys.error(s"$addr is not a Shelley payment address: $other")

    def resolve(raw: RawConfig): ResolvedConfig = {
        require(raw.boardPkhs.size == 3, s"expected 3 board pkhs, got ${raw.boardPkhs.size}")
        raw.boardPkhs.zipWithIndex.foreach { (p, i) =>
            require(p.matches("[0-9a-f]{56}"), s"boardPkhs[$i] is not a 56-char hex pkh: \"$p\"")
        }
        require(
          raw.fluidTokensPkh.matches("[0-9a-f]{56}"),
          s"fluidTokensPkh is not a 56-char hex pkh: \"${raw.fluidTokensPkh}\""
        )
        val tMs = BigInt(Instant.parse(raw.treasuryExpirationISO).toEpochMilli)
        val vMs = tMs + BigInt(raw.vendorExpirationGraceDays) * MsPerDay
        ResolvedConfig(
          network = raw.network,
          adminAddress = raw.adminAddress,
          adminPkhHex = addressPaymentKeyHash(raw.adminAddress),
          boardPkhs = raw.boardPkhs,
          fluidTokensPkh = raw.fluidTokensPkh,
          amountLovelace = raw.amountLovelace,
          treasuryExpirationMs = tMs,
          vendorExpirationMs = vMs,
          vendorPayoutUpperboundMs = tMs
        )
    }

    // ---- Concrete network configs (mirror params/preprod.ts) -----------------

    /** Bifrost Bridge — ₳12,332,031 ($0.16/ADA, incl. 10% contingency), T_max 2027-07-31, vendor
      * grace +30d. Two joint vendors (Lantr = K_op, FluidTokens) + production board K_1..K_3.
      * Preview re-uses these. See params/preprod.ts (bun parity counterpart).
      */
    val preprod: RawConfig = RawConfig(
      network = Net.Preprod,
      // K_op — Lantr operator (also Lantr vendor signer). Fresh key, 2026-07-02.
      adminAddress =
          "addr_test1qz0dmpgtyr6tyr7y555tkn707r9pnprs6gj2klthdvz99c7vcjy2fsjf8aenxn80lyr8czps6dh04jdsd40y8kcn9qrqvy0jxa",
      boardPkhs = Seq(
        "7095faf3d48d582fbae8b3f2e726670d7a35e2400c783d992bbdeffb", // K_1 — Matthias Benkort (CF)
        "058a5ab0c66647dcce82d7244f80bfea41ba76c7c9ccaf86a41b00fe", // K_2 — Chris Gianelloni (Blink Labs)
        "fe0921cfa53b2deef20f185258f8bc6e127ab6fa1084e62f0830ddef" // K_3 — Riley Kilgore (IOG)
      ),
      fluidTokensPkh = "1c471b31ea0b04c652bd8f76b239aea5f57139bdc5a2b28ab1e69175",
      amountLovelace = BigInt("12332031000000"),
      treasuryExpirationISO = "2027-07-31T00:00:00Z",
      vendorExpirationGraceDays = 30
    )

    val preview: RawConfig = preprod.copy(network = Net.Preview)

    // ---- Preview funding-flow TEST configs (stand-in keys) -------------------
    //
    // Same real K_op operator (keys/admin.*), but FluidTokens + board are
    // throwaway PREVIEW-ONLY stand-in keys (keys/test/*, generated by
    // `genTestKeys`) whose private keys we hold — so the test deployment can
    // actually satisfy every multisig path (disburse, fund, vendor-withdraw,
    // pause/resume, modify, sweep). NOT for mainnet. Distinct pkhs ⇒ distinct
    // script hashes ⇒ its own deployment file, isolated from the live preview
    // proposal deployment.

    private val testBoardPkhs = Seq(
      "25249f04490da3aacb7957a19025914f2a44f8512724947b86c7483e", // board1 (stand-in)
      "01af8ae80f7216323397201e46198919aeed40f133537d1b5368e01f", // board2 (stand-in)
      "48429d3937af58892bbeeac0a7b5fe8e7805a076a38ea867218a967a" // board3 (stand-in)
    )
    private val testFluidTokensPkh = "bc00dfa6e47e726ce1fc5f1a8867352d584ceee3b5d383ae5f24f474"

    /** Far T_max — no clock pressure for the operational scenarios. */
    val previewTest: RawConfig = preview.copy(
      boardPkhs = testBoardPkhs,
      fluidTokensPkh = testFluidTokensPkh
    )

    /** Short T_max + zero grace (vendor expiry == T_max) so treasury-sweep and
      * vendor-sweep are reachable in one sitting. Set `treasuryExpirationISO`
      * to ~1h ahead right before running its `init` (the value is baked into the
      * script hash, so it must stay fixed across that deployment's lifetime). */
    val previewTestSweep: RawConfig = previewTest.copy(
      treasuryExpirationISO = "2026-07-03T11:40:00Z",
      vendorExpirationGraceDays = 0
    )

    /** Mainnet — mirrors `params/mainnet.ts` (the bun parity counterpart). Same operator + board
      * keypair as preview/preprod: the payment pkh is identical; only the Shelley header byte (network
      * = 1) differs, so the `addr1…` form is just the mainnet encoding of the same admin key. Amount,
      * T_max, and grace are identical to preprod — same proposal, different network.
      */
    val mainnet: RawConfig = preprod.copy(
      network = Net.Mainnet,
      adminAddress =
          "addr1qx0dmpgtyr6tyr7y555tkn707r9pnprs6gj2klthdvz99c7vcjy2fsjf8aenxn80lyr8czps6dh04jdsd40y8kcn9qrq0jjj2z"
    )

    def forNetwork(net: Net): RawConfig = net match
        case Net.Preview => preview
        case Net.Preprod => preprod
        case Net.Mainnet => mainnet
}
