package treasurypublish

import java.nio.file.{Files, Path}

// Hash-parity gate: the Scala param-application must reproduce the script
// identities that the TypeScript SundaeSwap package produces. Oracle fixture is
// generated by scripts/parity-oracle.ts (deterministic, no network) for a fixed
// seed UTxO + preprodRawConfig. If this fails, the registry/treasury/vendor
// identities diverge from the audited TS path and nothing downstream is valid.
class ParitySuite extends munit.FunSuite {
    private lazy val fixture = {
        val p = Seq("treasury-publish/fixtures/parity-preprod.json", "fixtures/parity-preprod.json")
            .map(Path.of(_))
            .find(Files.exists(_))
            .getOrElse(sys.error("parity fixture not found"))
        ujson.read(Files.readString(p))
    }

    test("registry / treasury / vendor hashes match the TS oracle") {
        val seedTx = fixture("seed")("txId").str
        val seedIx = fixture("seed")("outputIndex").num.toLong
        val r = Config.resolve(Config.preprod)

        val registryPolicyHex = Scripts.registryPolicy(seedTx, seedIx).toHex
        assertEquals(
          registryPolicyHex,
          fixture("registryPolicy").str,
          "registry policy (oneshot applied with seed OutputReference) mismatch"
        )

        assertEquals(
          Scripts.treasuryScript(r, registryPolicyHex).scriptHash.toHex,
          fixture("treasuryScriptHash").str,
          "treasury script (applied with TreasuryConfiguration) mismatch"
        )

        assertEquals(
          Scripts.vendorScript(r, registryPolicyHex).scriptHash.toHex,
          fixture("vendorScriptHash").str,
          "vendor script (applied with VendorConfiguration) mismatch"
        )
    }

    test("registry datum (ScriptHashRegistry) encodes byte-for-byte vs the TS oracle") {
        import scalus.uplc.builtin.Builtins.serialiseData
        val seedTx = fixture("seed")("txId").str
        val seedIx = fixture("seed")("outputIndex").num.toLong
        val r = Config.resolve(Config.preprod)
        val registryPolicyHex = Scripts.registryPolicy(seedTx, seedIx).toHex
        val treasuryHex = Scripts.treasuryScript(r, registryPolicyHex).scriptHash.toHex
        val vendorHex = Scripts.vendorScript(r, registryPolicyHex).scriptHash.toHex
        assertEquals(
          serialiseData(ContractData.registryDatum(treasuryHex, vendorHex)).toHex,
          fixture("registryDatumHex").str
        )
    }

    test("admin payment key hash derives from the configured address") {
        val r = Config.resolve(Config.preprod)
        assertEquals(r.adminPkhHex, "9edd850b20f4b20fc4a528bb4fcff0ca198470d224ab7d776b0452e3")
    }

    test("registry asset name is REGISTRY") {
        assertEquals(Scripts.RegistryAssetNameHex, fixture("registryAssetNameHex").str)
    }

    test(
      "mainnet config mirrors preprod — same key identities, amount, T_max → same script hashes"
    ) {
        val mp = Config.resolve(Config.mainnet)
        val pp = Config.resolve(Config.preprod)
        assertEquals(Config.mainnet.network, Net.Mainnet)
        // The mainnet addr1… is the same operator key in network-1 form: parsing it
        // must yield the same payment pkh as the preprod addr_test1… form.
        assertEquals(mp.adminPkhHex, pp.adminPkhHex, "mainnet admin pkh must equal preprod")
        assertEquals(mp.boardPkhs, pp.boardPkhs, "board pkhs must match")
        assertEquals(mp.amountLovelace, pp.amountLovelace, "amount must match")
        assertEquals(mp.treasuryExpirationMs, pp.treasuryExpirationMs, "T_max must match")
        assertEquals(mp.vendorExpirationMs, pp.vendorExpirationMs, "vendor expiry must match")
        // Script identities are network-independent, so the mainnet config must
        // produce exactly the audited TS-oracle hashes (same as preprod/preview).
        val seedTx = fixture("seed")("txId").str
        val seedIx = fixture("seed")("outputIndex").num.toLong
        val pol = Scripts.registryPolicy(seedTx, seedIx).toHex
        assertEquals(
          Scripts.treasuryScript(mp, pol).scriptHash.toHex,
          fixture("treasuryScriptHash").str
        )
        assertEquals(
          Scripts.vendorScript(mp, pol).scriptHash.toHex,
          fixture("vendorScriptHash").str
        )
    }
}
