package treasurypublish

import java.nio.file.{Files, Path}

// Hash-parity gate: the Scala param-application must reproduce the script
// identities that the TypeScript SundaeSwap package produces. Oracle fixture is
// generated by scripts/parity-oracle.ts (deterministic, no network) for a fixed
// seed UTxO + preprodRawConfig. If this fails, the registry/treasury/vendor
// identities diverge from the audited TS path and nothing downstream is valid.
class ParitySuite extends munit.FunSuite {
    private lazy val fixture = {
        val p = Seq("treasury-publish/fixtures/parity-preprod.json", "fixtures/parity-preprod.json")
            .map(Path.of(_))
            .find(Files.exists(_))
            .getOrElse(sys.error("parity fixture not found"))
        ujson.read(Files.readString(p))
    }

    test("registry / treasury / vendor hashes match the TS oracle") {
        val seedTx = fixture("seed")("txId").str
        val seedIx = fixture("seed")("outputIndex").num.toLong
        val r = Config.resolve(Config.preprod)

        val registryPolicyHex = Scripts.registryPolicy(seedTx, seedIx).toHex
        assertEquals(
          registryPolicyHex,
          fixture("registryPolicy").str,
          "registry policy (oneshot applied with seed OutputReference) mismatch"
        )

        assertEquals(
          Scripts.treasuryScript(r, registryPolicyHex).scriptHash.toHex,
          fixture("treasuryScriptHash").str,
          "treasury script (applied with TreasuryConfiguration) mismatch"
        )

        assertEquals(
          Scripts.vendorScript(r, registryPolicyHex).scriptHash.toHex,
          fixture("vendorScriptHash").str,
          "vendor script (applied with VendorConfiguration) mismatch"
        )
    }

    test("registry datum (ScriptHashRegistry) encodes byte-for-byte vs the TS oracle") {
        import scalus.uplc.builtin.Builtins.serialiseData
        val seedTx = fixture("seed")("txId").str
        val seedIx = fixture("seed")("outputIndex").num.toLong
        val r = Config.resolve(Config.preprod)
        val registryPolicyHex = Scripts.registryPolicy(seedTx, seedIx).toHex
        val treasuryHex = Scripts.treasuryScript(r, registryPolicyHex).scriptHash.toHex
        val vendorHex = Scripts.vendorScript(r, registryPolicyHex).scriptHash.toHex
        assertEquals(
          serialiseData(ContractData.registryDatum(treasuryHex, vendorHex)).toHex,
          fixture("registryDatumHex").str
        )
    }

    test("admin payment key hash derives from the configured address") {
        val r = Config.resolve(Config.preprod)
        assertEquals(r.adminPkhHex, "2ecb28d3eea1e723e033cb63fbf5d90bc07aa8e986e04e2400d42104")
    }

    test("registry asset name is REGISTRY") {
        assertEquals(Scripts.RegistryAssetNameHex, fixture("registryAssetNameHex").str)
    }
}
