package treasurypublish

import scalus.uplc.builtin.ByteString
import scalus.crypto.ed25519.SigningKey

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path}

// Offline parity gate for the CIP-100 anchor signer: the Scala/scalus path
// (AnchorSigning, Titanium URDNA2015 + scalus ed25519) must reproduce, BYTE FOR
// BYTE, what the bun `jsonld`/blaze path produces. If this fails, a Scala-signed
// anchor witness would be rejected (or diverge from the bun-signed one) and the
// two pipelines are no longer in lockstep.
//
// Oracle fixture is generated by `bun run sign-parity-oracle` (deterministic, no
// network) from the committed stress anchor. Regenerate it and re-run this test
// whenever the fixture or the signing recipe changes.
class SignAnchorParitySuite extends munit.FunSuite {

    private def find(rels: String*): Path =
        rels.map(Path.of(_)).find(Files.exists(_)).getOrElse(sys.error(s"not found: $rels"))

    private lazy val anchor = ujson.read(
      Files.readString(
        find("treasury-publish/fixtures/anchor-sign-fixture.json", "fixtures/anchor-sign-fixture.json")
      )
    )
    private lazy val oracle = ujson.read(
      Files.readString(find("treasury-publish/fixtures/sign-parity.json", "fixtures/sign-parity.json"))
    )

    test("canonical N-Quads match the bun jsonld oracle byte-for-byte") {
        val nquads = new String(AnchorSigning.canonicalize(anchor), StandardCharsets.UTF_8)
        // Full-string compare: on mismatch munit shows a legible line diff.
        assertEquals(nquads, oracle("canonicalNQuads").str)
    }

    test("body blake2b-256 matches the oracle") {
        assertEquals(AnchorSigning.bodyHash(anchor).toHex, oracle("bodyHashHex").str)
    }

    test("ed25519 publicKey + signature match the oracle (fixed test key)") {
        val sk = SigningKey.unsafeFromByteString(ByteString.fromHex(oracle("testSecretKeyHex").str))
        val w = AnchorSigning.sign(anchor, sk)
        assertEquals(w.witnessAlgorithm, "ed25519")
        assertEquals(w.publicKeyHex, oracle("testPublicKeyHex").str, "publicKey mismatch")
        assertEquals(w.signatureHex, oracle("testSignatureHex").str, "signature mismatch")
    }
}
