#!/usr/bin/env bun
/**
 * Generate the offline golden fixture for the Scala anchor-signer parity test.
 *
 * Runs the exact CIP-100 recipe from sign-anchor.ts (URDNA2015 canonicalize →
 * blake2b-256 → ed25519) over the committed stress fixture
 * `treasury-publish/fixtures/anchor-sign-fixture.json`, signing with a FIXED,
 * committed, TEST-ONLY key. Emits `treasury-publish/fixtures/sign-parity.json`.
 *
 * The Scala test (sign-anchor.parity.test.scala) re-derives all of these with
 * Titanium + scalus and asserts byte-for-byte equality — proving the two
 * pipelines produce an identical author witness.
 *
 * Deterministic, no network. Regenerate (and re-run the scala test) whenever the
 * fixture or the signing recipe changes:
 *   bun run sign-parity-oracle
 *
 * Usage: bun scripts/sign-parity-oracle.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
// @ts-ignore - jsonld has CJS-only types that don't expose `canonize`
import jsonld from "jsonld";
import sodiumDefault from "libsodium-wrappers-sumo";
const sodium = sodiumDefault as unknown as {
  ready: Promise<void>;
  crypto_generichash: (outlen: number, input: Uint8Array) => Uint8Array;
};
import {
  Ed25519PrivateKey,
  Ed25519PrivateNormalKeyHex,
  HexBlob,
} from "@blaze-cardano/core";

const FIXTURE_PATH = "treasury-publish/fixtures/anchor-sign-fixture.json";
const OUT_PATH = "treasury-publish/fixtures/sign-parity.json";

/** FIXED test-only ed25519 key (32 bytes of 0x42). Not a real key — exists only
 *  so the Scala parity test can reproduce an identical publicKey + signature. */
const TEST_SECRET_KEY_HEX =
  "4242424242424242424242424242424242424242424242424242424242424242";

async function main(): Promise<void> {
  await sodium.ready;

  const anchor = JSON.parse(readFileSync(FIXTURE_PATH, "utf8"));
  const subset = { "@context": anchor["@context"], body: anchor.body };
  const canonize = (jsonld as { canonize: (...a: unknown[]) => Promise<string> })
    .canonize;
  const canonized = await canonize(subset, {
    algorithm: "URDNA2015",
    format: "application/n-quads",
    safe: true,
  });
  const canonicalNQuads = canonized.endsWith("\n") ? canonized : canonized + "\n";
  const payloadBytes = new TextEncoder().encode(canonicalNQuads);

  const bodyHashBytes = sodium.crypto_generichash(32, payloadBytes);
  const bodyHashHex = Buffer.from(bodyHashBytes).toString("hex");

  const sk = Ed25519PrivateKey.fromNormalHex(
    Ed25519PrivateNormalKeyHex(TEST_SECRET_KEY_HEX),
  );
  const testPublicKeyHex = sk.toPublic().hex();
  const testSignatureHex = sk.sign(HexBlob(bodyHashHex)).hex();

  const fixture = {
    _comment:
      "GENERATED by scripts/sign-parity-oracle.ts. Golden fixture for treasury-publish/sign-anchor.parity.test.scala. Do not hand-edit; regenerate with `bun run sign-parity-oracle`.",
    canonicalNQuads,
    bodyHashHex,
    testSecretKeyHex: TEST_SECRET_KEY_HEX,
    testPublicKeyHex,
    testSignatureHex,
  };
  writeFileSync(OUT_PATH, JSON.stringify(fixture, null, 2) + "\n");

  console.log(`Wrote ${OUT_PATH}`);
  console.log(`  canonical N-Quads : ${payloadBytes.byteLength} bytes`);
  console.log(`  body blake2b-256  : ${bodyHashHex}`);
  console.log(`  test publicKey    : ${testPublicKeyHex}`);
  console.log(`  test signature    : ${testSignatureHex.slice(0, 32)}…`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
